apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: https://github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://34.69.52.207:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CsQCChgKFggCGgYIypv0gQYiCmFsbGNoYW5uZWwSpwIKpAIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgoKBkFkbWlucxIAIg8KC0VuZG9y
      c2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSABqwARKtAQoLQXBwbGljYXRpb24SnQEI
      ARKYAQoKY2Fycmllck1TUBKJAQgBGj0KC0FuY2hvclBlZXJzEi4SJAoiCh1wZWVyMC5jYXJyaWVy
      LW5ldC5leGFtcGxlLmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgoKBkFkbWlucxIAIg8KC0VuZG9y
      c2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

