apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-mychannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-mychannel-carrier
  chart:
    git: https://github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://35.226.55.1:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: mychannel      
    orderer:
      address: orderer.supplychain-net:7050
    anchorstx: |-
      CsICChcKFQgCGgYIuOi6gQYiCW15Y2hhbm5lbBKmAgqjAgoJbXljaGFubmVsEmMSYQoLQXBwbGlj
      YXRpb24SUggBEk4KCmNhcnJpZXJNU1ASQBoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRvcnNl
      bWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAasAESrQEKC0FwcGxpY2F0aW9uEp0BCAES
      mAEKCmNhcnJpZXJNU1ASiQEIARo9CgtBbmNob3JQZWVycxIuEiQKIgodcGVlcjAuY2Fycmllci1u
      ZXQuY2Fycmllci1uZXQQ+0EaBkFkbWlucxoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRvcnNl
      bWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAqBkFkbWlucw==

