apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: ssh://git@github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://104.197.165.69:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CsoCChgKFggCGgYInKCagQYiCmFsbGNoYW5uZWwSrQIKqgIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIg8KC0VuZG9yc2VtZW50EgAiCwoH
      UmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSABq2ARKzAQoLQXBwbGljYXRpb24SowEI
      ARKeAQoKY2Fycmllck1TUBKPAQgBGkMKC0FuY2hvclBlZXJzEjQSKgooCiNwZWVyMC5jYXJyaWVy
      LW5ldC5kZXZlbG9wLmxvY2FsLmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgoKBkFkbWlucxIAIg8K
      C0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

