apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-twinbiotchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-twinbiotchannel
  chart:
    git: ssh://git@github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://35.222.174.152:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: twinbiotchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CuMDCh0KGwgCGgYImNGVgQYiD3R3aW5iaW90Y2hhbm5lbBLBAwq+AwoPdHdpbmJpb3RjaGFubmVs
      EkYSNAoLQXBwbGljYXRpb24SJRIOCgpjYXJyaWVyTVNQEgASEwoPbWFudWZhY3R1cmVyTVNQEgAa
      DgoKQ29uc29ydGl1bRIAGuICErYCCgtBcHBsaWNhdGlvbhKmAggBEg4KCmNhcnJpZXJNU1ASABIT
      Cg9tYW51ZmFjdHVyZXJNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5z
      IiwKC0VuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyI1ChRMaWZlY3lj
      bGVFbmRvcnNlbWVudBIdEhMIAxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiIgoHUmVhZGVycxIX
      Eg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxonCgpDb25zb3J0
      aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt