apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: example-net-ca
  namespace: example-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: example-net-ca
  chart:
    git: https://github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: example-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: example-admin
    storage:
      storageclassname: examplesc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://34.69.50.148:8200
      authpath: example-net-auth
      secretcert: secret/crypto/ordererOrganizations/example-net/ca?ca.example-net-cert.pem
      secretkey: secret/crypto/ordererOrganizations/example-net/ca?example-net-CA.key
      secretadminpass: secret/credentials/example-net/ca/example?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
