apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-mychannel-manufacturer
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-mychannel-manufacturer
  chart:
    git: https://github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://35.226.55.1:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: mychannel      
    orderer:
      address: orderer.supplychain-net:7050
    anchorstx: |-
      CtcCChcKFQgCGgYI+qq6gQYiCW15Y2hhbm5lbBK7Agq4AgoJbXljaGFubmVsEmgSZgoLQXBwbGlj
      YXRpb24SVwgBElMKD21hbnVmYWN0dXJlck1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdX
      cml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABrAARK9AQoLQXBwbGljYXRpb24S
      rQEIARKoAQoPbWFudWZhY3R1cmVyTVNQEpQBCAEaBwoDTVNQEgAaSAoLQW5jaG9yUGVlcnMSORIv
      Ci0KKHBlZXIwLm1hbnVmYWN0dXJlci1uZXQuZGV2ZWxvcC5sb2NhbC5jb20Q+0EaBkFkbWlucyIP
      CgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAqBkFk
      bWlucw==

