apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-net-ca-tools
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-net-ca-tools
  chart:
    git: ssh://git@github.com/brando14/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: warehouse-net
      name: ca-tools

    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      
    storage:
      storageclassname: warehousesc
      storagesize: 512Mi
